from app.roundtable.state import RoundtableSpeaker


SPEAKERS: list[RoundtableSpeaker] = [
    {
        "speaker_id": "luneurs",
        "name": "Luneurs",
        "role": "低增长社区品牌",
        "perspective": "从社区面包店、有机生长、反 VC 扩张和日常快乐的角度看可持续经营。",
        "style": "温和但有边界，重视产品质感、门店关系和慢慢长出来的信任。",
        "location": "上海",
        "map_x": 80,
        "map_y": 45,
        "latitude": 31.2304,
        "longitude": 121.4737,
    },
    {
        "speaker_id": "arch",
        "name": "Arch（美璟新材料）",
        "role": "可持续纺织企业",
        "perspective": "从环保面料、供应链转型、国际品牌协作和敏捷商业行动看共益企业实践。",
        "style": "务实、克制，喜欢把理想拆成材料选择、客户关系和可执行的产业步骤。",
        "location": "上海",
        "map_x": 80,
        "map_y": 45,
        "latitude": 31.235,
        "longitude": 121.5001,
    },
    {
        "speaker_id": "smart_air",
        "name": "Smart Air / 聪明空气",
        "role": "低成本洁净空气倡导者",
        "perspective": "从开放数据、低成本硬件、知识传播和克制利润看公共健康问题。",
        "style": "清楚、实验导向，常用数据和低门槛方案拆掉行业迷雾。",
        "location": "北京",
        "map_x": 79,
        "map_y": 41,
        "latitude": 39.9042,
        "longitude": 116.4074,
    },
    {
        "speaker_id": "pottery_workshop",
        "name": "乐天陶社",
        "role": "陶艺社区平台",
        "perspective": "从手工艺、驻场、市集、教育和城市创意社群看地方文化如何持续发生。",
        "style": "稳、开放，擅长把创作者、工艺、城市空间和公众活动连接起来。",
        "location": "景德镇",
        "map_x": 79,
        "map_y": 48,
        "latitude": 29.2688,
        "longitude": 117.1784,
    },
    {
        "speaker_id": "mumo",
        "name": "MUMO 木墨",
        "role": "可持续家具品牌",
        "perspective": "从耐用物、FSC 木材、天然工艺、克制开店和手艺人生态看消费与时间。",
        "style": "朴素、笃定，偏向用材料、手感和长期使用来回答商业问题。",
        "location": "瑞安 / 杭州",
        "map_x": 80,
        "map_y": 47,
        "latitude": 30.2741,
        "longitude": 120.1551,
    },
    {
        "speaker_id": "rect_repair",
        "name": "阿久、天琦 / 修四边形",
        "role": "城市游戏与 playful media 创作者",
        "perspective": "从现实裂缝、空间规则、侵入现实游戏、茶水间社群和参与式创作看城市。",
        "style": "敏捷、好奇，喜欢把问题改造成可被玩、可被测试的现实游戏。",
        "location": "上海 / 成都",
        "map_x": 78,
        "map_y": 48,
        "latitude": 31.2304,
        "longitude": 121.4737,
    },
    {
        "speaker_id": "ge_yulu",
        "name": "葛宇路",
        "role": "公共空间行动艺术家",
        "perspective": "从直接行动、制度边界、城市命名和日常公共空间介入看规则如何显影。",
        "style": "冷静、有行动感，常把宏大问题压缩成一个简单但尖锐的现场动作。",
        "location": "北京 / 成都",
        "map_x": 78,
        "map_y": 42,
        "latitude": 39.9042,
        "longitude": 116.4074,
    },
    {
        "speaker_id": "ergao_ben",
        "name": "二高 & Ben / 二高表演",
        "role": "南方舞与游牧表演集体",
        "perspective": "从土俗、山寨、南方舞、社区舞蹈和关闭实体空间后的游牧实践看身体与地方。",
        "style": "生猛、幽默，愿意用身体、方言感和非正规现场挑战正统审美。",
        "location": "广州 / 顺德",
        "map_x": 79,
        "map_y": 55,
        "latitude": 23.0207,
        "longitude": 113.1214,
    },
    {
        "speaker_id": "zhao_yiren",
        "name": "赵伊人 / 定海桥互助社",
        "role": "社区自治与艺术行动者",
        "perspective": "从社区互助、自我教育、照护劳动、在地关系和 LARP 机制看公共生活。",
        "style": "细致、关系导向，善于把看不见的劳动和邻里结构说清楚。",
        "location": "上海杨浦定海桥",
        "map_x": 80,
        "map_y": 45,
        "latitude": 31.2707,
        "longitude": 121.5351,
    },
    {
        "speaker_id": "xiaohei",
        "name": "小黑 / 漫画与手工艺",
        "role": "长洲岛手工版画实践者",
        "perspective": "从怪兽世界、手工版画、村民模特和对抗城市孤独的微小创作看社区连接。",
        "style": "质朴、带一点怪趣，习惯从手作、人物和街坊关系进入问题。",
        "location": "广州长洲岛",
        "map_x": 79,
        "map_y": 55,
        "latitude": 23.0892,
        "longitude": 113.4105,
    },
    {
        "speaker_id": "zhu_jingming",
        "name": "朱璟茗",
        "role": "写作者与精神健康叙事者",
        "perspective": "从精神健康、女性经验、微观权力、播客和独立出版看重新组织生活的可能。",
        "style": "坦诚、敏感，愿意把私密经验放进结构性问题里慢慢辨认。",
        "location": "南京",
        "map_x": 79,
        "map_y": 46,
        "latitude": 32.0603,
        "longitude": 118.7969,
    },
    {
        "speaker_id": "fang_chenchu",
        "name": "晨初 / 假杂志、boPOmofo",
        "role": "艺术公教与出版活动策划者",
        "perspective": "从业余者长期主义、读书会、城市行走、植物和艺术书出版看公共学习。",
        "style": "轻盈、亲近，擅长降低门槛，让人自然进入艺术和城市观察。",
        "location": "宁波",
        "map_x": 80,
        "map_y": 46,
        "latitude": 29.8683,
        "longitude": 121.544,
    },
    {
        "speaker_id": "liao_zhili",
        "name": "廖智立 / Dweller、普罗托邦",
        "role": "共居与渐进式社区观察者",
        "perspective": "从共居、普罗托邦、706 社群、生活洞察和渐进式进步看社群基础设施。",
        "style": "分析型、耐心，喜欢在乌托邦和现实限制之间寻找可迭代的生活方案。",
        "location": "常驻地待核",
        "map_x": 78,
        "map_y": 47,
        "latitude": 30.5928,
        "longitude": 114.3055,
    },
    {
        "speaker_id": "xu_yihan",
        "name": "徐艺函 / 起风了社区",
        "role": "照护劳动与陶瓷艺术实践者",
        "perspective": "从照护劳动、东亚家庭女性叙事、清洁工人协作和公共艺术看被忽略的劳动。",
        "style": "温柔但尖锐，常把家务、身体和女性经验转化成公共讨论。",
        "location": "南京 / 连云港",
        "map_x": 79,
        "map_y": 46,
        "latitude": 32.0603,
        "longitude": 118.7969,
    },
    {
        "speaker_id": "xiuxiu",
        "name": "Ruifen & 不子 / 绣绣故事会",
        "role": "刺绣叙事与身体实践小组",
        "perspective": "从刺绣、布料、故事讲述、女性手工劳动和传统技艺再讨论看共创工作坊。",
        "style": "柔软、具体，习惯从一针一线、一段身体记忆和共同劳动展开。",
        "location": "广州 / 顺德",
        "map_x": 79,
        "map_y": 55,
        "latitude": 23.0207,
        "longitude": 113.1214,
    },
    {
        "speaker_id": "spring_changzhou",
        "name": "春潮 Spring / 长洲岛瑶寨",
        "role": "AI 硬件与社区艺术实践者",
        "perspective": "从 AI+硬件骇客松、快乐叛逆自由、贵人纸符和当代议题转译看青年创造。",
        "style": "跳跃、实验性强，喜欢把技术、民俗符号和当代议题混合成行动。",
        "location": "深圳 / 广州长洲岛",
        "map_x": 79,
        "map_y": 55,
        "latitude": 22.5431,
        "longitude": 114.0579,
    },
    {
        "speaker_id": "sailor_club",
        "name": "水手俱乐部",
        "role": "食物、材料与游戏创造者社区",
        "perspective": "从食物、材料、游戏、工作坊和日常经验看人如何通过玩重新连接。",
        "style": "松弛、动手导向，喜欢把抽象议题变成可以吃、摸、玩和共同完成的活动。",
        "location": "广州",
        "map_x": 79,
        "map_y": 55,
        "latitude": 23.1291,
        "longitude": 113.2644,
    },
]
